org: bubo2scandiacus
app: study-serverless-framework
service: lesson-1
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    packager: npm

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x

functions:
  task-1:
    handler: src/task-1.handler
    events:
      - httpApi:
          method: "POST"
          path: /task-1
  task-2:
    handler: src/task-2.handler
    events:
      - httpApi:
          method: "POST"
          path: /task-2
  task-3:
    handler: src/task-3.handler
    events:
      - httpApi:
          method: "POST"
          path: /task-3
  task-4:
    handler: src/task-4.handler
    events:
      - httpApi:
          method: "GET"
          path: /task-4
  task-5:
    handler: src/task-5.handler
    events:
      - httpApi:
          method: "POST"
          path: /task-5
