org: bubo2scandiacus
app: study-serverless-framework
service: lesson-1
frameworkVersion: "3"

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    packager: npm

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x

functions:
  hello:
    handler: src/hello.handler
